In [6]:
import numpy as np
import pandas as pd

In [19]:
import torch
import transformers


model = transformers.AutoModelForTokenClassification.from_pretrained(
    'numind/entity-recognition-general-sota-v1',
    output_hidden_states=True
)
lowercased_tokenizer = transformers.AutoTokenizer.from_pretrained("numind/entity-recognition-general-sota-v1", do_lower_case=False, add_prefix_space=True)


text = [
    "NuMind is an AI company based in Paris and USA.",
    "NuMind est une entreprise d'IA basée à Paris et aux États-Unis.",
    "See other models from us on https://huggingface.co/numind"
]

config.json:   0%|          | 0.00/666 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaForTokenClassification were not initialized from the model checkpoint at numind/entity-recognition-general-sota-v1 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


tokenizer_config.json:   0%|          | 0.00/1.34k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/999k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/957 [00:00<?, ?B/s]

In [25]:
encoded_input = lowercased_tokenizer(
    text[0],
    return_tensors='pt',
    padding=True,
    truncation=True
)
# output = model(**encoded_input)

# output

In [31]:
output1 = model(**encoded_input)
output1.keys()

odict_keys(['logits', 'hidden_states'])

In [28]:
output = model(encoded_input.input_ids)

In [29]:
output.keys()

odict_keys(['logits', 'hidden_states'])

In [39]:
output.hidden_states

(tensor([[[ 0.1664, -0.0541, -0.0014,  ..., -0.0811,  0.0794,  0.0155],
          [-0.5248,  0.2801,  0.4486,  ...,  0.0110, -0.0439,  0.6628],
          [-0.5238,  0.0197,  0.5519,  ..., -0.5611, -0.0806,  0.0699],
          ...,
          [ 0.1860,  0.2763, -0.1049,  ...,  0.0151, -0.0041, -0.0166],
          [ 0.4389,  0.0708, -0.0174,  ..., -0.7510,  0.0380,  0.0565],
          [ 0.2013, -0.0754, -0.0824,  ...,  0.5229,  0.0814, -0.1648]]],
        grad_fn=<NativeLayerNormBackward0>),
 tensor([[[-0.0386,  0.0406,  0.0129,  ...,  0.0055,  0.0191, -0.1568],
          [-0.3830,  0.6166,  0.4740,  ...,  0.0019, -0.0428,  0.8373],
          [-0.3998,  0.4703,  0.4742,  ..., -1.0079, -0.1454,  0.4028],
          ...,
          [ 0.2743,  0.5231,  0.1479,  ..., -0.2509,  0.0639, -0.3067],
          [ 0.1453,  0.1753,  0.1593,  ..., -0.1004, -0.0678, -0.0262],
          [-0.5472,  0.2210,  0.0582,  ...,  0.8652, -0.0906, -0.5900]]],
        grad_fn=<NativeLayerNormBackward0>),
 tensor([[[ 

In [36]:
output1.logits

tensor([[[ 0.5939, -0.5554],
         [ 0.4796, -0.6792],
         [ 0.6052, -0.6192],
         [ 0.5560, -0.3665],
         [ 0.6973, -0.1530],
         [ 0.7569, -0.3676],
         [ 0.9570, -0.5516],
         [ 0.9601, -0.2552],
         [ 0.8162, -0.3915],
         [ 0.5917, -0.0897],
         [ 0.5492, -0.3379],
         [ 0.7679, -0.3024],
         [ 0.8092, -0.3597],
         [ 0.6174, -0.6227]]], grad_fn=<ViewBackward0>)

In [32]:
output.logits

tensor([[[ 0.5939, -0.5554],
         [ 0.4796, -0.6792],
         [ 0.6052, -0.6192],
         [ 0.5560, -0.3665],
         [ 0.6973, -0.1530],
         [ 0.7569, -0.3676],
         [ 0.9570, -0.5516],
         [ 0.9601, -0.2552],
         [ 0.8162, -0.3915],
         [ 0.5917, -0.0897],
         [ 0.5492, -0.3379],
         [ 0.7679, -0.3024],
         [ 0.8092, -0.3597],
         [ 0.6174, -0.6227]]], grad_fn=<ViewBackward0>)

In [ ]:
output1 =

In [43]:
# two emb trick: for better quality
emb = torch.cat(
    (output.hidden_states[-1], output.hidden_states[-7]),
    dim=2
)
emb

tensor([[[ 0.2242,  0.0661,  0.7835,  ...,  0.0300, -0.0453, -0.0419],
         [ 0.2320,  0.1378,  0.7239,  ...,  0.0125, -0.0404, -0.2213],
         [ 0.1130,  0.2562,  0.6859,  ..., -0.8474, -0.6329,  0.1879],
         ...,
         [-0.0957,  0.1228,  0.6111,  ..., -0.1879,  0.2293, -0.2184],
         [ 0.1147,  0.1913,  0.3666,  ..., -0.0202, -0.0433, -0.0218],
         [-0.0546,  0.2287,  0.5275,  ...,  0.6231,  0.4346, -0.2874]]],
       grad_fn=<CatBackward0>)

In [46]:
len(encoded_input.input_ids[0]) #14 tokens

14

In [47]:
emb.shape

torch.Size([1, 14, 1536])